/**
 * careers.js — 6 个冒险少年职业定义。
 * 主题:中世纪 / 宗教 / 龙族 / 飞行 / 远洋冒险。
 * 每个职业:背景故事 + 起始牌组 + 特色卡 + 关键数值。
 *
 * 卡组 ID 必须能在 data.js CARDS 里找到,或为本职业特色卡(此处扩展)。
 */

export const CAREERS = [
  {
    id: 'swordsman',
    name: '剑术学徒',
    root: '剑术',        // 职介晋升后与职衔后缀合成(如 剑术教授)
    title: '钢铁之誓',
    color: '#c0392b',
    icon: '⚔',
    maxHp: 75,
    energyMax: 3,
    mpMax: 2,
    backstory: '你出身于王国边境的铁匠世家,自幼在锤声与火星中长大。十二岁那年,一头黑龙焚毁了你的村庄,你被剑术大师收养,在冰原剑塔中磨砺十年。如今剑塔倾颓,你背起父亲的旧剑,踏上寻找弟弟与归乡的路。',
    starterDeck: ['strike', 'strike', 'strike', 'defend', 'defend', 'cleave', 'shield_bash', 'pommel'],
    signatureCards: ['riposte', 'iron_will'],
  },
  {
    id: 'mage',
    name: '魔法学徒',
    root: '魔法',
    title: '星图执笔',
    color: '#8e44ad',
    icon: '✦',
    maxHp: 60,
    energyMax: 4,
    mpMax: 6,
    backstory: '你是典学院最年轻的星象学徒,能从夜空中读出命运轨迹。当大祭司以"净化"之名焚毁古籍、拘押异说孩童时,你抱着一卷被禁的星图逃离学院。星图指向龙脊山脉,那里藏着揭开真相的钥匙,也指向你失散的弟弟。',
    starterDeck: ['strike', 'defend', 'insight', 'insight', 'arcane_bolt', 'arcane_bolt', 'flex', 'recover'],
    signatureCards: ['arcane_bolt', 'starfall'],
  },
  {
    id: 'cavalier',
    name: '骑兵新兵',
    root: '骑兵',
    title: '风行之蹄',
    color: '#27ae60',
    icon: '♞',
    maxHp: 80,
    energyMax: 3,
    mpMax: 2,
    backstory: '你是王国骑兵团的弃儿,因身世不洁被逐出军营。马背上长大的你,带着一匹受伤的军马流落乡野。当你听说弟弟被"龙脊教团"掳走,便策马踏上漫漫寻亲路。马蹄踏过的每一寸土地,都在替你丈量正义的距离。',
    starterDeck: ['strike', 'strike', 'strike', 'defend', 'charge', 'charge', 'pommel', 'defend'],
    signatureCards: ['charge', 'trample'],
  },
  {
    id: 'aviator',
    name: '飞行学徒',
    root: '飞行',
    title: '云端之翼',
    color: '#3498db',
    icon: '✈',
    maxHp: 65,
    energyMax: 3,
    mpMax: 3,
    backstory: '你生于云端浮岛族,自幼与风鸥为伴。弟弟被龙带走的那个黄昏,你跌下浮岛,被飞行学院收留。如今你以学徒之身驾驭初阶风翼,在云层之间追踪那道焚天的赤红龙影。天空是你的家,也是你寻回弟弟的唯一路径。',
    starterDeck: ['strike', 'defend', 'dive', 'dive', 'insight', 'defend', 'cleave', 'flex'],
    signatureCards: ['dive', 'gust'],
  },
  {
    id: 'mariner',
    name: '航海学徒',
    root: '航海',
    title: '盐风之子',
    color: '#16a085',
    icon: '⚓',
    maxHp: 70,
    energyMax: 3,
    mpMax: 3,
    backstory: '你出生于远洋渔家,父亲死于一场突如其来的海妖之乱。母亲改嫁后,继父将弟弟卖给龙脊教团做祭品。你逃离家门,登上商船当杂役,横渡墨色之海。每一道浪都在问你:为了寻回弟弟,你愿意潜入多深的海。',
    starterDeck: ['strike', 'strike', 'defend', 'defend', 'tide', 'tide', 'recover', 'insight'],
    signatureCards: ['tide', 'tsunami'],
  },
  {
    id: 'theologian',
    name: '经典学徒',
    root: '经典',
    title: '烛火之间',
    color: '#f1c40f',
    icon: '🕯',
    maxHp: 65,
    energyMax: 3,
    mpMax: 5,
    backstory: '你是大神殿最虔诚的烛火学徒,每日为神像擦拭金箔。直到某夜,你听见神像背后传来弟弟的哭声——他被作为"献祭"封入圣坛。你撕下典士袍,带着偷出的古卷残页,踏上揭穿教团伪神的路。信仰不是枷锁,而是你出鞘的剑。',
    starterDeck: ['strike', 'defend', 'defend', 'bless', 'bless', 'insight', 'recover', 'pommel'],
    signatureCards: ['bless', 'judgement'],
  },
  // ===== 第二大章解锁职业:治疗师(healer) =====
  {
    id: 'healer',
    name: '治疗师',
    root: '治疗',
    title: '龙魂医者',
    color: '#2ecc71',
    icon: '✚',
    maxHp: 70,
    energyMax: 3,
    mpMax: 4,
    backstory: '在龙骨荒原,你得到了远古龙魂的祝福。那股温暖的力量不仅能增强你的攻击力,还能治愈伤口。在联军营地,你系统地学习了如何运用这股治疗之力,成为了联军里第一位「治疗师」——一个能用龙魂之力治愈伤口、提升士气的特殊职业。',
    starterDeck: ['strike', 'defend', 'defend', 'heal_touch', 'heal_touch', 'sanctuary', 'insight', 'recover'],
    signatureCards: ['heal_touch', 'group_heal'],
    passive: { id: 'dragon_vitality', name: '龙魂活力', desc: '每次剧情推进(章节切换)额外恢复 2 点行动力' },
  },
  // ===== 法师进阶:白魔法师(white_mage) =====
  {
    id: 'white_mage',
    name: '白魔法师',
    root: '白魔',
    title: '圣光使者',
    color: '#ecf0f1',
    icon: '☀',
    maxHp: 62,
    energyMax: 3,
    mpMax: 7,
    backstory: '你通过了龙神的试炼,成为了一名正式的白魔法师。你掌握了治愈与守护之力,获得了龙神的祝福和圣光之衣。从今往后,你将用这股力量,守护你所爱的人,守护这片大陆的和平。',
    starterDeck: ['strike', 'defend', 'holy_light', 'holy_light', 'divine_shield', 'holy_smite', 'insight', 'recover'],
    signatureCards: ['holy_light', 'holy_storm'],
  },
  // ===== 法师进阶:黑魔法师(black_mage) =====
  {
    id: 'black_mage',
    name: '黑魔法师',
    root: '黑魔',
    title: '暗影使者',
    color: '#8e44ad',
    icon: '☾',
    maxHp: 58,
    energyMax: 3,
    mpMax: 7,
    backstory: '你通过了暗影试炼,成为了一名正式的黑魔法师。你掌握了破坏与毁灭之力,获得了龙神的祝福和暗影之袍。从今往后,你将用这股力量,扫清一切阻碍,赢得这场战争的胜利。',
    starterDeck: ['strike', 'defend', 'shadow_bolt', 'shadow_bolt', 'curse', 'hellfire', 'insight', 'arcane_bolt'],
    signatureCards: ['shadow_bolt', 'void_rift'],
  },
  // ===== 第三章新增:经典师(classic) — 纯辅助职业 =====
  // 起源:远古洞穴中的上古典籍,龙族传授给人类的削弱之道
  // 特点:降低敌方攻击力、魔力、减少抗伤害能力、持续扣血
  {
    id: 'classic',
    name: '经典师',
    root: '经典',
    title: '龙纹典守',
    color: '#d4a017',
    icon: '📖',
    maxHp: 65,
    energyMax: 3,
    mpMax: 5,
    backstory: '在远古洞穴中,你发现了龙族留给人类的上古典籍,记录着"经典师"的修炼之道。经典师是龙族传授给人类的纯辅助职业,擅长以言灵和符文削弱敌人——降低攻击力、抑制魔力、瓦解防御、持续侵蚀。经典师不直接攻击,而是让敌人在不知不觉中衰弱。你的使命不是战斗,而是守护真相。',
    starterDeck: ['defend', 'defend', 'insight', 'insight', 'weaken', 'disrupt', 'erode', 'recover'],
    signatureCards: ['weaken', 'ancient_curse'],
    passive: { id: 'word_spirit', name: '言灵之力', desc: '每回合开始时,对最弱敌人施加1层虚弱(攻击力-2)' },
  },
];

export const CAREER_MAP = Object.fromEntries(CAREERS.map((c) => [c.id, c]));
